[tool.poetry]
name = "new-ara-api"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"
djangorestframework = "^3.10"
django-s3-storage = "^0.12.5"
django-cors-headers = "^3.1"
django-debug-toolbar = "^2.0"
django-mysql = "^3.2"
requests = "^2.22"
beautifulsoup4 = "^4.8"
django-extensions = "^2.2"
djangorestframework-filters = "^1.0.0.dev0"
drf-yasg = "^1.17"
mysqlclient = "^1.4"
bleach = "^3.1"
Pillow = "^6.2"
django-environ = "^0.4.5"
gunicorn = "^19.9"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
autopep8 = "^1.4"
pylint-django = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
